name: Create Archive
on: [push]
# This is a comment, and this is used to force a run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: 8
          format: "YYYYMMDDHHmmss"
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "bnp-pack.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig .github"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: V.0.${{ github.run_number }}
          release_name: Pack_Release v.0.${{ github.run_number }}
          draft: false
          prerelease: false


      - name: Upload Modpack Release Asset
        id: upload-modpack-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./bnp-pack.zip
          asset_name: bnp-pack.zip
          asset_content_type: application/zip